[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.17.7"
hex = "0.4.3"
sha2 = "0.11.0-pre.2"
ripemd = "0.1.3"
bs58 = "0.5.0"
digest = "0.11.0-pre.7"
bitcoin_hashes = "0.13.0"